#!/usr/bin/env python3

# This file is entirely generated by Artificial Intelligence (AI). License may be vague.

"""
mm_server: the simcard-server HTTP API, backed by the SIM in a ModemManager
managed QMI modem instead of a PC/SC reader.

Same API as server.py (USIM-https-server compatible, plain HTTP):

  GET /?type=imsi
      -> {"imsi": "311480..."}

  GET /?type=rand-autn&rand=<32 hex>&autn=<32 hex>[&app=isim]
      -> {"res": "<hex>", "ck": "<hex>", "ik": "<hex>"}
      app=isim (an extension, for IMS AKA) runs it on the ISIM, over a
      logical channel of its own, or on the USIM if the card has no ISIM.
      On AKA synchronisation failure (AUTS in "res", as SWu-IKEv2 expects):
      -> {"res": "<auts>", "ck": null, "ik": null, "auts": "<28 hex>"}

  GET /?type=apdu&hex=<apdu hex>
      Raw APDU on the USIM logical channel (CLA channel bits are rewritten).
      -> {"data": "<hex>", "sw": "9000"}

It does not disturb the modem's own use of the SIM or an active data session:

  * The IMSI comes from ModemManager's SIM object over D-Bus; the card is not
    touched for it.
  * AUTHENTICATE runs on a dedicated QMI UIM *logical channel* opened through
    qmi-proxy, the same proxy ModemManager uses. That is a separate session from
    MM's basic-channel access, so the two never collide. AT+CSIM is avoided on
    purpose: it rides the basic channel and wedges QMI modems when MM is active.

    sudo python3 mm_server.py                            # first QMI modem
    sudo python3 mm_server.py --modem 0 --listen 127.0.0.1:8888
    sudo python3 mm_server.py --listen 127.0.0.1:8443 --tls-cert sim.pem
    sudo python3 mm_server.py --probe                    # IMSI + channel test

Requires ModemManager, libqmi with GObject introspection (python3-gi, Qmi-1.0)
and root (qmi-proxy only accepts root clients).
"""
from __future__ import annotations

import argparse
import atexit
import json
import os
import signal
import socket
import socketserver
import ssl
import sys
import threading
from http.server import BaseHTTPRequestHandler
from urllib.parse import parse_qs, urlparse

import gi

gi.require_version("Qmi", "1.0")
from gi.repository import Gio, GLib, Qmi  # noqa: E402

MM_BUS = "org.freedesktop.ModemManager1"
MM_PATH = "/org/freedesktop/ModemManager1"
MM_MODEM = "org.freedesktop.ModemManager1.Modem"
MM_SIM = "org.freedesktop.ModemManager1.Sim"
MM_PORT_QMI = 6          # MMModemPortType
MM_PORT_MBIM = 7

USIM_AID_PREFIX = bytes.fromhex("A0000000871002")
ISIM_AID_PREFIX = bytes.fromhex("A0000000871004")
QMI_TIMEOUT = 10         # seconds per QMI request

DEFAULT_UNIX_SOCKET = "/run/nekoims/simcard.sock"


class CardError(Exception):
    pass


class NoApplication(CardError):
    """The card status lists the card's applications and this isn't one."""


def log(msg: str):
    print(msg, file=sys.stderr, flush=True)


# -- ModemManager (D-Bus) ---------------------------------------------------

def _mm_prop(path: str, iface: str, name: str):
    bus = Gio.bus_get_sync(Gio.BusType.SYSTEM, None)
    v = bus.call_sync(MM_BUS, path, "org.freedesktop.DBus.Properties", "Get",
                      GLib.Variant("(ss)", (iface, name)),
                      GLib.VariantType("(v)"), Gio.DBusCallFlags.NONE,
                      5000, None)
    return v.unpack()[0]


def mm_modems() -> list[str]:
    bus = Gio.bus_get_sync(Gio.BusType.SYSTEM, None)
    v = bus.call_sync(MM_BUS, MM_PATH, "org.freedesktop.DBus.ObjectManager",
                      "GetManagedObjects", None, None, Gio.DBusCallFlags.NONE,
                      5000, None)
    return sorted(p for p, ifaces in v.unpack()[0].items() if MM_MODEM in ifaces)


class Modem:
    """The ModemManager modem we use: its QMI port and SIM object."""

    def __init__(self, selector: str | None):
        self.selector = selector
        self.path = self.qmi_dev = self.sim_path = None

    def resolve(self):
        """(Re)discover the modem; it moves to a new index after a reset."""
        try:
            modems = mm_modems()
        except GLib.Error as e:
            raise CardError(f"ModemManager not reachable: {e.message}")
        if not modems:
            raise CardError("ModemManager reports no modems")

        sel = self.selector
        if sel is None:
            candidates = modems
        elif sel.startswith("/"):
            candidates = [p for p in modems if p == sel]
        elif sel.isdigit():
            candidates = [p for p in modems if p.rsplit("/", 1)[1] == sel]
        else:  # equipment identifier (IMEI)
            candidates = [p for p in modems
                          if _mm_prop(p, MM_MODEM, "EquipmentIdentifier") == sel]
        if not candidates:
            raise CardError(f"no ModemManager modem matches '{sel}'")

        for path in candidates:
            ports = _mm_prop(path, MM_MODEM, "Ports")
            qmi = [n for n, t in ports if t == MM_PORT_QMI]
            if not qmi:
                if any(t == MM_PORT_MBIM for _, t in ports):
                    log(f"{path}: MBIM-only modem, not supported (needs QMI)")
                continue
            sim = _mm_prop(path, MM_MODEM, "Sim")
            if not sim or sim == "/":
                raise CardError(f"{path}: no SIM")
            self.path, self.qmi_dev, self.sim_path = path, f"/dev/{qmi[0]}", sim
            return
        raise CardError("no ModemManager modem with a QMI port")

    def imsi(self) -> str | None:
        if not self.sim_path:
            self.resolve()
        try:
            imsi = _mm_prop(self.sim_path, MM_SIM, "Imsi")
        except GLib.Error:
            self.resolve()
            imsi = _mm_prop(self.sim_path, MM_SIM, "Imsi")
        return imsi if imsi and imsi.isdigit() else None


# -- QMI UIM logical channel ------------------------------------------------

class QmiUimChannel:
    """One QMI UIM client and logical channel to the USIM (or the ISIM, for
    IMS AKA), via qmi-proxy.

    libqmi is asynchronous and bound to a GLib main context, so a dedicated
    thread owns the context and every operation is run on it.
    """

    def __init__(self, slot: int, aid: bytes | None, app: str = "usim"):
        self.slot = slot
        self.app = app
        self.fixed_aid = aid
        self.aid = None
        self.dev_path = None
        self.device = None
        self.client = None
        self.channel = None

        self.ctx = GLib.MainContext.new()
        self.loop = GLib.MainLoop.new(self.ctx, False)
        self.thread = threading.Thread(target=self._run, daemon=True,
                                       name=f"qmi-{app}")
        self.thread.start()

    def _run(self):
        self.ctx.push_thread_default()
        self.loop.run()

    def call(self, fn, *args):
        """Run fn(*args) on the QMI thread and return its result."""
        done = threading.Event()
        box = {}

        def job():
            try:
                box["value"] = fn(*args)
            except Exception as e:  # handed back to the caller's thread
                box["error"] = e
            done.set()
            return GLib.SOURCE_REMOVE

        src = GLib.idle_source_new()
        src.set_callback(job)
        src.attach(self.ctx)
        done.wait()
        if "error" in box:
            raise box["error"]
        return box["value"]

    def _wait(self, begin, finish):
        """Start an async libqmi call and iterate our context until it ends."""
        box = {}

        def cb(_source, result, _data=None):
            try:
                box["value"] = finish(result)
            except GLib.Error as e:
                box["error"] = e

        begin(cb)
        while not box:
            self.ctx.iteration(True)
        if "error" in box:
            raise CardError(box["error"].message)
        return box["value"]

    # -- setup / teardown (QMI thread only) --------------------------------

    def _open_device(self, dev_path: str):
        f = Gio.File.new_for_path(dev_path)
        dev = self._wait(lambda cb: Qmi.Device.new(f, None, cb, None),
                         Qmi.Device.new_finish)
        self._wait(lambda cb: dev.open(Qmi.DeviceOpenFlags.PROXY, QMI_TIMEOUT,
                                       None, cb, None),
                   dev.open_finish)
        client = self._wait(lambda cb: dev.allocate_client(
                                Qmi.Service.UIM, 0, QMI_TIMEOUT, None, cb,
                                None),
                            dev.allocate_client_finish)
        self.device, self.client, self.dev_path = dev, client, dev_path

    def _app_aid(self) -> bytes:
        if self.fixed_aid:
            return self.fixed_aid
        want = (Qmi.UimCardApplicationType.ISIM if self.app == "isim"
                else Qmi.UimCardApplicationType.USIM)
        prefix = ISIM_AID_PREFIX if self.app == "isim" else USIM_AID_PREFIX
        try:
            out = self._wait(lambda cb: self.client.get_card_status(
                                 None, QMI_TIMEOUT, None, cb, None),
                             self.client.get_card_status_finish)
            out.get_result()
            cards = out.get_card_status()[-1]
            listed = False
            for card in cards:
                for app in card.applications:
                    listed = True
                    if app.type == want:
                        return bytes(app.application_identifier_value)
        except Exception as e:  # GI struct access varies between versions
            log(f"card status lookup failed ({e}); using partial "
                f"{self.app.upper()} AID")
            listed = False
        if listed:
            raise NoApplication(f"no {self.app.upper()} on the card")
        # ISO 7816-4 partial DF name selection: RID + application code
        return prefix

    def _open_channel(self):
        aid = self._app_aid()
        inp = Qmi.MessageUimOpenLogicalChannelInput.new()
        inp.set_slot(self.slot)
        inp.set_aid(list(aid))
        out = self._wait(lambda cb: self.client.open_logical_channel(
                             inp, QMI_TIMEOUT, None, cb, None),
                         self.client.open_logical_channel_finish)
        try:
            out.get_result()
        except GLib.Error as e:
            raise CardError(f"open logical channel to {aid.hex()} failed: "
                            f"{e.message}")
        self.channel = out.get_channel_id()
        self.aid = aid
        log(f"QMI UIM logical channel {self.channel} ({self.app.upper()}) "
            f"open on {self.dev_path}, AID {aid.hex().upper()}")

    def _close(self):
        if self.client and self.channel is not None:
            inp = Qmi.MessageUimLogicalChannelInput.new()
            inp.set_slot(self.slot)
            inp.set_channel_id(self.channel)
            try:
                self._wait(lambda cb: self.client.logical_channel(
                               inp, QMI_TIMEOUT, None, cb, None),
                           self.client.logical_channel_finish)
                log(f"closed QMI UIM logical channel {self.channel}")
            except CardError as e:
                log(f"closing channel {self.channel} failed: {e}")
        self.channel = None
        if self.device and self.client:
            try:
                self._wait(lambda cb: self.device.release_client(
                               self.client,
                               Qmi.DeviceReleaseClientFlags.RELEASE_CID,
                               QMI_TIMEOUT, None, cb, None),
                           self.device.release_client_finish)
            except CardError:
                pass
        self.client = None
        if self.device:
            try:
                self._wait(lambda cb: self.device.close_async(
                               QMI_TIMEOUT, None, cb, None),
                           self.device.close_finish)
            except CardError:
                pass
        self.device = None

    def _ensure(self, dev_path: str):
        if self.device and self.dev_path != dev_path:
            self._close()
        if not self.device:
            self._open_device(dev_path)
        if self.channel is None:
            self._open_channel()

    # -- APDU transport (QMI thread only) ----------------------------------

    def _cla(self, cla: int) -> int:
        ch = self.channel
        if ch <= 3:
            return (cla & 0xFC) | ch
        return (cla & 0xB0) | 0x40 | ((ch - 4) & 0x0F)

    def _send_raw(self, apdu: bytes) -> bytes:
        inp = Qmi.MessageUimSendApduInput.new()
        inp.set_slot(self.slot)
        inp.set_channel_id(self.channel)
        inp.set_apdu(list(bytes([self._cla(apdu[0])]) + apdu[1:]))
        out = self._wait(lambda cb: self.client.send_apdu(
                             inp, QMI_TIMEOUT, None, cb, None),
                         self.client.send_apdu_finish)
        try:
            out.get_result()
        except GLib.Error as e:
            raise CardError(f"send APDU failed: {e.message}")
        resp = bytes(out.get_apdu_response())
        if len(resp) < 2:
            raise CardError("short APDU response")
        return resp

    def _xmit(self, apdu: bytes):
        resp = self._send_raw(apdu)
        data, sw1, sw2 = resp[:-2], resp[-2], resp[-1]
        if sw1 == 0x6C and len(apdu) >= 5:   # wrong Le -> resend
            resp = self._send_raw(apdu[:-1] + bytes([sw2]))
            data, sw1, sw2 = resp[:-2], resp[-2], resp[-1]
        while sw1 == 0x61:                    # more data -> GET RESPONSE
            resp = self._send_raw(bytes([0x00, 0xC0, 0x00, 0x00, sw2]))
            data, sw1, sw2 = data + resp[:-2], resp[-2], resp[-1]
        return data, sw1, sw2

    def transmit(self, dev_path: str, apdu: bytes):
        """Send one APDU; on failure reopen everything and retry once."""
        try:
            self._ensure(dev_path)
            return self._xmit(apdu)
        except NoApplication:
            raise
        except CardError as e:
            log(f"QMI error ({e}), reopening channel")
            self._close()
            self._ensure(dev_path)
            return self._xmit(apdu)

    def shutdown(self):
        self._close()
        self.loop.quit()


# -- USIM operations --------------------------------------------------------

class Usim:
    def __init__(self, modem: Modem, chan: QmiUimChannel,
                 isim_chan: QmiUimChannel | None = None):
        self.modem = modem
        self.chan = chan
        self.isim_chan = isim_chan  # opened on the first IMS AKA
        self.no_isim = False
        self.lock = threading.Lock()

    def _xmit(self, apdu: bytes, chan: QmiUimChannel | None = None):
        chan = chan or self.chan
        if not self.modem.qmi_dev:
            self.modem.resolve()
        try:
            return chan.call(chan.transmit, self.modem.qmi_dev, apdu)
        except NoApplication:
            raise
        except CardError:
            # The modem may have re-enumerated (new index / port) after a reset.
            self.modem.resolve()
            return chan.call(chan.transmit, self.modem.qmi_dev, apdu)

    def imsi(self) -> str:
        with self.lock:
            imsi = self.modem.imsi()
            if imsi:
                return imsi
            # MM has no IMSI yet: read EF.IMSI on the channel (ADF selected)
            _, sw1, sw2 = self._xmit(bytes.fromhex("00A40004026F0700"))
            if sw1 != 0x90:
                raise CardError(f"SELECT EF.IMSI failed: SW={sw1:02X}{sw2:02X}")
            raw, sw1, sw2 = self._xmit(bytes.fromhex("00B0000009"))
        if sw1 != 0x90 or not raw or raw[0] > len(raw) - 1:
            raise CardError(f"READ EF.IMSI failed: SW={sw1:02X}{sw2:02X}")
        digits = "".join(f"{b & 0x0F:x}{b >> 4:x}" for b in raw[1:1 + raw[0]])
        digits = digits[1:].rstrip("f")
        if not digits.isdigit() or not 14 <= len(digits) <= 15:
            raise CardError(f"implausible IMSI {digits!r}")
        return digits

    def authenticate(self, rand: bytes, autn: bytes,
                     isim: bool = False) -> dict:
        """UMTS AKA (AUTHENTICATE, 3G context), on the ISIM if asked and the
        card has one. Returns hex RES/CK/IK or AUTS."""
        body = bytes([len(rand)]) + rand + bytes([len(autn)]) + autn
        apdu = bytes([0x00, 0x88, 0x00, 0x81, len(body)]) + body + b"\x00"
        with self.lock:
            chan = None
            if isim and self.isim_chan and not self.no_isim:
                chan = self.isim_chan
            try:
                data, sw1, sw2 = self._xmit(apdu, chan)
            except NoApplication as e:
                # Only when the card status says so; other ISIM errors fail
                # the AKA rather than silently using the wrong application.
                log(f"{e}, IMS AKA runs on the USIM")
                self.no_isim = True
                data, sw1, sw2 = self._xmit(apdu)

        if sw1 == 0x98 and sw2 == 0x62:
            raise CardError("authentication error: MAC failure (AUTN rejected)")
        if sw1 != 0x90 or not data:
            raise CardError(f"AUTHENTICATE failed: SW={sw1:02X}{sw2:02X}")

        tag, p = data[0], 1
        if tag == 0xDC:  # synchronisation failure
            n = data[p]
            auts = data[p + 1:p + 1 + n].hex()
            # SWu-IKEv2 / USIM-https-server put AUTS in "res" with null CK/IK
            return {"res": auts, "ck": None, "ik": None, "auts": auts}
        if tag != 0xDB:
            raise CardError(f"unexpected AUTHENTICATE response tag {tag:02X}")

        out = {}
        for name in ("res", "ck", "ik"):
            n = data[p]
            out[name] = data[p + 1:p + 1 + n].hex()
            p += 1 + n
        return out

    def apdu(self, apdu: bytes) -> dict:
        with self.lock:
            data, sw1, sw2 = self._xmit(apdu)
        return {"data": data.hex(), "sw": f"{sw1:02X}{sw2:02X}"}


# -- HTTP -------------------------------------------------------------------

def parse_hex(q: dict, name: str, length: int | None = None) -> bytes:
    try:
        value = bytes.fromhex(q[name][0])
    except (KeyError, IndexError, ValueError):
        raise ValueError(f"missing or invalid hex parameter '{name}'")
    if length is not None and len(value) != length:
        raise ValueError(f"'{name}' must be {length} bytes")
    return value


class Handler(BaseHTTPRequestHandler):
    server_version = "NekoIMS-simcard-mm/1.0"
    usim: Usim = None  # set in main()

    def address_string(self):
        return self.client_address[0] if self.client_address else "unix"

    def _reply(self, code: int, obj: dict):
        body = json.dumps(obj).encode()
        self.send_response(code)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self):
        q = parse_qs(urlparse(self.path).query)
        kind = q.get("type", [""])[0]
        try:
            if kind == "imsi":
                self._reply(200, {"imsi": self.usim.imsi()})
            elif kind == "rand-autn":
                rand = parse_hex(q, "rand", 16)
                autn = parse_hex(q, "autn", 16)
                isim = q.get("app", [""])[0] == "isim"
                self._reply(200, self.usim.authenticate(rand, autn, isim))
            elif kind == "apdu":
                self._reply(200, self.usim.apdu(parse_hex(q, "hex")))
            else:
                self._reply(400, {"error": f"unknown type '{kind}'"})
        except ValueError as e:
            self._reply(400, {"error": str(e)})
        except CardError as e:
            self._reply(502, {"error": str(e)})
        except Exception as e:
            self._reply(503, {"error": f"{type(e).__name__}: {e}"})


class ThreadingUnixHTTPServer(socketserver.ThreadingMixIn,
                              socketserver.UnixStreamServer):
    daemon_threads = True


class ThreadingTCPHTTPServer(socketserver.ThreadingMixIn,
                             socketserver.TCPServer):
    daemon_threads = True
    allow_reuse_address = True


def make_tcp_server(listen: str, cert: str | None, key: str | None):
    host, _, port = listen.rpartition(":")
    host = host.strip("[]")
    cls = ThreadingTCPHTTPServer
    if ":" in host:
        cls = type("V6", (ThreadingTCPHTTPServer,),
                   {"address_family": socket.AF_INET6})
    srv = cls((host, int(port)), Handler)
    if not cert:
        return srv, f"http://{listen}"
    tls = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    tls.load_cert_chain(cert, key)
    srv.socket = tls.wrap_socket(srv.socket, server_side=True)
    return srv, f"https://{listen}"


def unix_socket_in_use(path: str) -> bool:
    """Whether another server is accepting on path. Two servers sharing the
    card interleave APDUs (e.g. SELECT failing with 6F00), and starting one
    would unlink the other's socket."""
    s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    try:
        s.settimeout(1)
        s.connect(path)
        return True
    except OSError:
        return False
    finally:
        s.close()


def make_unix_server(unix_path: str):
    os.makedirs(os.path.dirname(unix_path), mode=0o750, exist_ok=True)
    if os.path.exists(unix_path):
        os.unlink(unix_path)
    srv = ThreadingUnixHTTPServer(unix_path, Handler)
    os.chmod(unix_path, 0o660)
    return srv, f"unix:{unix_path}"


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--modem", default=None,
                    help="ModemManager modem index, D-Bus path or IMEI "
                         "(default: first modem with a QMI port)")
    ap.add_argument("--slot", type=int, default=1, help="UIM slot (default 1)")
    ap.add_argument("--aid", default=None,
                    help="USIM AID in hex (default: from the card status)")
    ap.add_argument("--unix", default=DEFAULT_UNIX_SOCKET,
                    help=f"Unix socket path (default: {DEFAULT_UNIX_SOCKET})")
    ap.add_argument("--no-unix", action="store_true",
                    help="do not listen on the Unix socket")
    ap.add_argument("--listen", default=None,
                    help="also listen on TCP HOST:PORT (e.g. for SWu-IKEv2)")
    ap.add_argument("--tls-cert", default=None,
                    help="serve HTTPS on --listen with this PEM certificate")
    ap.add_argument("--tls-key", default=None,
                    help="private key for --tls-cert (default: in the cert)")
    ap.add_argument("--probe", action="store_true",
                    help="read the IMSI, open the channel, then exit")
    args = ap.parse_args()

    if args.no_unix and not args.listen:
        ap.error("--no-unix needs --listen")
    if args.tls_cert and not args.listen:
        ap.error("--tls-cert needs --listen")
    for path in (args.tls_cert, args.tls_key):
        if path and not os.access(path, os.R_OK):
            ap.error(f"cannot read TLS file {path}")

    if os.geteuid() != 0:
        sys.exit("mm_server must run as root: qmi-proxy only accepts root "
                 "clients")
    if not args.no_unix and unix_socket_in_use(args.unix):
        sys.exit(f"another SIM server is already serving {args.unix}")

    modem = Modem(args.modem)
    chan = QmiUimChannel(args.slot,
                         bytes.fromhex(args.aid) if args.aid else None)
    isim_chan = QmiUimChannel(args.slot, None, "isim")
    usim = Usim(modem, chan, isim_chan)
    atexit.register(lambda: chan.call(chan.shutdown))
    atexit.register(lambda: isim_chan.call(isim_chan.shutdown))
    # Run atexit (and so release the channel) on SIGTERM too.
    signal.signal(signal.SIGTERM, lambda *_: sys.exit(0))

    try:
        modem.resolve()
        log(f"modem {modem.path}, QMI port {modem.qmi_dev}, SIM {modem.sim_path}")
        log(f"USIM IMSI: {usim.imsi()}")
        # Open the channel now so a broken setup fails at startup.
        st = usim.apdu(bytes.fromhex("80F2000000"))   # STATUS on the ADF
        if st["sw"] != "9000":
            raise CardError(f"STATUS on the USIM channel returned {st['sw']}")
    except CardError as e:
        sys.exit(f"cannot use the modem SIM: {e}")

    if args.probe:
        log("probe OK")
        return

    Handler.usim = usim
    servers = []
    try:
        if not args.no_unix:
            servers.append(make_unix_server(args.unix))
        if args.listen:
            servers.append(make_tcp_server(args.listen, args.tls_cert,
                                           args.tls_key))
    except (OSError, ssl.SSLError) as e:
        sys.exit(f"cannot listen: {e}")

    for srv, where in servers:
        threading.Thread(target=srv.serve_forever, daemon=True).start()
        log(f"simcard-server (ModemManager) listening on {where}")
    try:
        signal.pause()
    except KeyboardInterrupt:
        pass
    finally:
        for srv, _ in servers:
            srv.shutdown()
            srv.server_close()
        if not args.no_unix and os.path.exists(args.unix):
            os.unlink(args.unix)

if __name__ == "__main__":
    main()
