#!/usr/bin/env bash
# This file is entirely generated by Artificial Intelligence (AI). License may be vague.
#
# start.sh: build NekoIMS if needed, start the SIM server for whatever SIM is
# attached (PC/SC reader or ModemManager modem), write the config, dial the
# ePDG with the static strongSwan build and run NekoIMS in the tunnel netns.
#
#   ./start.sh [options] [-- nekoims args...]
#
#   --sim pcsc|mm     SIM backend (default: autodetect, PC/SC reader first)
#   --reader N        PC/SC reader index (pcsc)
#   --modem M         ModemManager modem index, path or IMEI (mm)
#   --config PATH     NekoIMS config (default: generated by mkconfig for mm,
#                     /etc/nekoims/config.json for pcsc)
#   --remote URL      static strongSwan tarball for the dialer, {arch} expands
#                     to x86_64/arm64 (default: latest neko-strongswan release)
#   --charon PATH     use an installed charon instead of --remote
#   --rebuild         rebuild NekoIMS even if build/nekoims exists
#
# Everything after -- goes to nekoims (e.g. -- -v -t). Ctrl-C or quitting
# NekoIMS hangs up the tunnel and stops what this script started.
set -euo pipefail

REPO=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
BUILD=$REPO/build
RUN_DIR=/run/nekoims
SOCK=$RUN_DIR/simcard.sock
PCSCF_FILE=$RUN_DIR/pcscf
NETNS=ims
REMOTE_DEFAULT='https://github.com/MercuryWorkshop/neko-strongswan/releases/latest/download/linux-strongswan-{arch}.tar.gz'
DIAL_TIMEOUT=90

SIM=auto READER= MODEM= CONFIG= REMOTE= CHARON= REBUILD=0
NEKOIMS_ARGS=()
SUDO_ARGS=()  # our arguments minus --rebuild, for the re-run under sudo
for a in "$@"; do [ "$a" = --rebuild ] || SUDO_ARGS+=("$a"); done

die() { echo "start.sh: $*" >&2; exit 1; }
log() { echo "start.sh: $*" >&2; }

while [ $# -gt 0 ]; do
	case $1 in
		--sim)		SIM=${2:?}; shift ;;
		--reader)	READER=${2:?}; shift ;;
		--modem)	MODEM=${2:?}; shift ;;
		--config)	CONFIG=${2:?}; shift ;;
		--remote)	REMOTE=${2:?}; shift ;;
		--charon)	CHARON=${2:?}; shift ;;
		--rebuild)	REBUILD=1 ;;
		--)			shift; NEKOIMS_ARGS=("$@"); break ;;
		-h|--help)	sed -n '4,21p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
		*)			die "unknown option $1 (see --help)" ;;
	esac
	shift
done
case $SIM in auto|pcsc|mm) ;; *) die "--sim must be pcsc or mm" ;; esac
[ -n "$REMOTE" ] && [ -n "$CHARON" ] && die "--remote and --charon are exclusive"

# -- 1. build (as the invoking user, never as root) ---------------------------

if [ ! -x "$BUILD/nekoims" ] || [ "$REBUILD" = 1 ]; then
	command -v cmake >/dev/null || die "cmake not found"
	AS_USER=()
	if [ "$(id -u)" = 0 ] && [ -n "${SUDO_USER:-}" ]; then
		AS_USER=(sudo -u "$SUDO_USER" --)
	fi
	log "building NekoIMS"
	if [ ! -f "$BUILD/CMakeCache.txt" ]; then
		"${AS_USER[@]}" cmake -S "$REPO" -B "$BUILD" -DCMAKE_BUILD_TYPE=Release
	fi
	"${AS_USER[@]}" cmake --build "$BUILD" -j"$(nproc)"
fi
[ -x "$BUILD/nekoims" ] || die "build did not produce $BUILD/nekoims"

if [ "$(id -u)" != 0 ]; then
	log "root needed for the SIM server, tunnel and netns, re-running with sudo"
	exec sudo -- "$0" "${SUDO_ARGS[@]}"
fi

# -- cleanup ------------------------------------------------------------------

SIM_PID= DIAL_PID=
cleanup() {
	trap - EXIT INT TERM
	if [ -n "$DIAL_PID" ] && kill -0 "$DIAL_PID" 2>/dev/null; then
		log "hanging up the ePDG tunnel"
		kill -TERM "$DIAL_PID" 2>/dev/null || true
		wait "$DIAL_PID" 2>/dev/null || true
	fi
	if [ -n "$SIM_PID" ] && kill -0 "$SIM_PID" 2>/dev/null; then
		kill -TERM "$SIM_PID" 2>/dev/null || true
		wait "$SIM_PID" 2>/dev/null || true
	fi
}
trap cleanup EXIT
trap 'exit 130' INT TERM

mkdir -p "$RUN_DIR"
chmod 750 "$RUN_DIR"

# One start.sh at a time. Children get fd 9 closed so leftovers can't hold it.
exec 9>"$RUN_DIR/start.lock"
flock -n 9 || die "another start.sh is already running"

# Processes a previous run left behind (e.g. its terminal was killed). A second
# dialer would fight over charon, a second SIM server over the card.
leftovers() { pgrep -f "$REPO/$1" | tr '\n' ' ' || true; }
DIALERS=$(leftovers 'dialers/strongswan-dialer\.py')
[ -z "$DIALERS" ] || die "a dialer is already running (pid $DIALERS), stop it: sudo kill $DIALERS"

# -- 2. SIM server ------------------------------------------------------------

sim_up() {
	python3 - "$SOCK" <<'EOF' 2>/dev/null
import http.client, socket, sys
class C(http.client.HTTPConnection):
    def connect(self):
        self.sock = socket.socket(socket.AF_UNIX)
        self.sock.settimeout(5)
        self.sock.connect(sys.argv[1])
c = C("sim")
c.request("GET", "/?type=imsi")
sys.exit(0 if c.getresponse().status == 200 else 1)
EOF
}

have_pcsc() {  # a reader with a card in it
	python3 - <<'EOF' 2>/dev/null
import sys
from smartcard.System import readers
for r in readers():
    try:
        c = r.createConnection()
        c.connect()
        c.disconnect()
        sys.exit(0)
    except Exception:
        pass
sys.exit(1)
EOF
}

have_mm() {
	command -v mmcli >/dev/null || return 1
	local m
	for m in $(mmcli -L 2>/dev/null | grep -o '/org/freedesktop/ModemManager1/Modem/[0-9]*'); do
		mmcli -m "$m" -K 2>/dev/null |
			grep -qE '^modem\.generic\.sim +: /org/freedesktop/ModemManager1/SIM/' &&
			return 0
	done
	return 1
}

if [ "$SIM" = auto ]; then
	if have_pcsc; then
		SIM=pcsc
		have_mm && log "ModemManager also has a SIM; using PC/SC, pass --sim mm for the modem"
	elif have_mm; then
		SIM=mm
	else
		die "no SIM found: no PC/SC reader (pcscd + pyscard) and no ModemManager modem with a SIM"
	fi
fi
log "SIM backend: $SIM"

if sim_up; then
	log "reusing the SIM server already on $SOCK"
else
	SERVERS=$(leftovers 'simcard-server/(server|mm_server)\.py')
	[ -z "$SERVERS" ] || die "a SIM server is running (pid $SERVERS) but not \
answering on $SOCK, stop it: sudo kill $SERVERS"
	if [ "$SIM" = pcsc ]; then
		python3 "$REPO/simcard-server/server.py" ${READER:+--reader "$READER"} 9>&- &
	else
		python3 "$REPO/simcard-server/mm_server.py" ${MODEM:+--modem "$MODEM"} 9>&- &
	fi
	SIM_PID=$!
	for _ in $(seq 50); do
		sim_up && break
		kill -0 "$SIM_PID" 2>/dev/null || die "SIM server exited"
		sleep 0.2
	done
	sim_up || die "SIM server did not come up on $SOCK"
fi

# -- 3. config ----------------------------------------------------------------

if [ -z "$CONFIG" ]; then
	if [ "$SIM" = mm ]; then
		CONFIG=$RUN_DIR/config.json
		log "generating $CONFIG with mkconfig"
		python3 "$REPO/tools/mkconfig.py" ${MODEM:+--modem "$MODEM"} \
			-o "$CONFIG" --force
	else
		CONFIG=/etc/nekoims/config.json
		[ -f "$CONFIG" ] || die "no $CONFIG: mkconfig needs ModemManager, so for \
a PC/SC SIM copy nekoims.example.json there (or pass --config)"
	fi
fi
[ -f "$CONFIG" ] || die "config $CONFIG not found"
if python3 -c 'import json, sys; sys.exit(0 if json.load(open(sys.argv[1])).get("pcscf") else 1)' \
	"$CONFIG" 2>/dev/null; then
	log "warning: $CONFIG sets \"pcscf\", which overrides the one the ePDG assigns"
fi

# -- 4. dial ------------------------------------------------------------------

DIAL_ARGS=()
if [ -n "$CHARON" ]; then
	DIAL_ARGS+=(--charon "$CHARON")
else
	DIAL_ARGS+=(--remote "${REMOTE:-$REMOTE_DEFAULT}")
fi
DIAL_LOG=$RUN_DIR/dialer.log
rm -f "$PCSCF_FILE"
log "dialing the ePDG (log: $DIAL_LOG)"
python3 "$REPO/dialers/strongswan-dialer.py" "${DIAL_ARGS[@]}" >"$DIAL_LOG" 2>&1 9>&- &
DIAL_PID=$!

for _ in $(seq $((DIAL_TIMEOUT * 5))); do
	[ -s "$PCSCF_FILE" ] && break
	if ! kill -0 "$DIAL_PID" 2>/dev/null; then
		tail -n 25 "$DIAL_LOG" >&2
		die "dialer exited before the tunnel came up"
	fi
	sleep 0.2
done
if [ ! -s "$PCSCF_FILE" ]; then
	tail -n 25 "$DIAL_LOG" >&2
	die "no P-CSCF from the ePDG after ${DIAL_TIMEOUT}s"
fi
grep -E '^tunnel up' "$DIAL_LOG" >&2 || true
log "P-CSCF: $(head -n1 "$PCSCF_FILE")"

# -- 5. NekoIMS ---------------------------------------------------------------

log "starting NekoIMS in netns $NETNS"
set +e

ip netns exec "$NETNS" "$BUILD/nekoims" -c "$CONFIG" "${NEKOIMS_ARGS[@]}" 9>&-
RC=$?
set -e
exit "$RC"
