#!/usr/bin/env python3

# This file is entirely generated by Artificial Intelligence (AI). License may be vague.

"""
mkconfig: generate nekoims.json from ModemManager and a carrier bundle.

ModemManager provides the subscriber and device identity (IMSI, MSISDN,
IMEI, MCC/MNC). Operator specifics (IMS domain, transport, headers) come
from carrier-bundles/<digits>.json, picked by the longest IMSI prefix; with no
bundle the 3GPP discovery names (TS 23.003) are used. The P-CSCF changes with
every ePDG session, so it is normally passed to nekoims with -p; --pcscf here
stores one in the file instead.

    sudo python3 tools/mkconfig.py -o /etc/nekoims/config.json [--force]
    sudo ip netns exec ims ./build/nekoims -p <pcscf>

Needs no root: ModemManager exposes these properties to any user.
"""
from __future__ import annotations

import argparse
import glob
import json
import os
import re
import sys

import gi
from gi.repository import Gio, GLib  # noqa: E402

MM_BUS = "org.freedesktop.ModemManager1"
MM_PATH = "/org/freedesktop/ModemManager1"
MM_MODEM = "org.freedesktop.ModemManager1.Modem"
MM_SIM = "org.freedesktop.ModemManager1.Sim"

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BUNDLES_DEFAULT = os.path.join(REPO, "carrier-bundles")
SIMCARD_SERVER_DEFAULT = "unix:/run/nekoims/simcard.sock"

# Bundle keys copied into nekoims.json as-is.
CONFIG_KEYS = ("domain", "transport", "pcscf_port", "p_access_network_info",
               "contact_features", "expires", "user_agent", "sms")

# MCCs in the North American Numbering Plan (+1).
NANP_MCCS = {"302"} | {str(m) for m in range(310, 317)}


def log(msg: str):
    print(msg, file=sys.stderr)


def mm_prop(path: str, iface: str, name: str):
    bus = Gio.bus_get_sync(Gio.BusType.SYSTEM, None)
    v = bus.call_sync(MM_BUS, path, "org.freedesktop.DBus.Properties", "Get",
                      GLib.Variant("(ss)", (iface, name)),
                      GLib.VariantType("(v)"), Gio.DBusCallFlags.NONE,
                      5000, None)
    return v.unpack()[0]


def find_modem(selector: str | None) -> str:
    bus = Gio.bus_get_sync(Gio.BusType.SYSTEM, None)
    v = bus.call_sync(MM_BUS, MM_PATH, "org.freedesktop.DBus.ObjectManager",
                      "GetManagedObjects", None, None, Gio.DBusCallFlags.NONE,
                      5000, None)
    modems = sorted(p for p, ifs in v.unpack()[0].items() if MM_MODEM in ifs)
    if not modems:
        sys.exit("ModemManager reports no modems")
    if selector is None:
        return modems[0]
    for p in modems:
        if (p == selector or p.rsplit("/", 1)[1] == selector or
                mm_prop(p, MM_MODEM, "EquipmentIdentifier") == selector):
            return p
    sys.exit(f"no ModemManager modem matches '{selector}'")


def find_bundle(imsi: str, bundles_dir: str):
    """The bundle whose digit name is the longest prefix of the IMSI."""
    best, best_len = None, -1
    for path in glob.glob(os.path.join(bundles_dir, "*.json")):
        digits = re.sub(r"\D", "", os.path.splitext(os.path.basename(path))[0])
        if digits and imsi.startswith(digits) and len(digits) > best_len:
            best, best_len = path, len(digits)
    if not best:
        return None, None
    with open(best) as f:
        return json.load(f), os.path.basename(best)


def discovery_bundle(mcc: str, mnc: str) -> dict:
    """TS 23.003 13.2 / 19.4.2.4 names for an operator without a bundle."""
    mnc3 = mnc.zfill(3)
    return {
        "name": f"MCC {mcc} / MNC {mnc} (3GPP discovery)",
        "domain": f"ims.mnc{mnc3}.mcc{mcc}.3gppnetwork.org",
        "epdg": f"epdg.epc.mnc{mnc3}.mcc{mcc}.pub.3gppnetwork.org",
        "apn": "ims",
    }


def e164(number: str, mcc: str) -> str | None:
    digits = re.sub(r"[^\d+]", "", number)
    if digits.startswith("+"):
        return digits
    if mcc in NANP_MCCS:
        if len(digits) == 10:
            return "+1" + digits
        if len(digits) == 11 and digits.startswith("1"):
            return "+" + digits
    return None


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--pcscf", default=None,
                    help="store this P-CSCF in the file (normally given to "
                         "nekoims with -p instead)")
    ap.add_argument("--modem", default=None,
                    help="ModemManager modem index, D-Bus path or IMEI "
                         "(default: first modem)")
    ap.add_argument("--msisdn", default=None,
                    help="E.164 number, overrides the SIM's own number")
    ap.add_argument("--simcard-server", default=SIMCARD_SERVER_DEFAULT,
                    help=f"(default: {SIMCARD_SERVER_DEFAULT})")
    ap.add_argument("--bundles-dir", default=BUNDLES_DEFAULT)
    ap.add_argument("-o", "--output", default=None,
                    help="write here instead of stdout")
    ap.add_argument("--force", action="store_true",
                    help="overwrite an existing --output file")
    args = ap.parse_args()

    if args.output and os.path.exists(args.output) and not args.force:
        sys.exit(f"{args.output} exists; pass --force to overwrite it")

    try:
        modem = find_modem(args.modem)
        sim = mm_prop(modem, MM_MODEM, "Sim")
        if not sim or sim == "/":
            sys.exit(f"{modem}: no SIM")
        imsi = mm_prop(sim, MM_SIM, "Imsi")
        mccmnc = mm_prop(sim, MM_SIM, "OperatorIdentifier")
        imei = mm_prop(modem, MM_MODEM, "EquipmentIdentifier")
        own = list(mm_prop(modem, MM_MODEM, "OwnNumbers") or [])
    except GLib.Error as e:
        sys.exit(f"ModemManager: {e.message}")

    if not imsi or not imsi.isdigit():
        sys.exit("ModemManager has no IMSI for this SIM (is it unlocked?)")
    mcc = imsi[:3]
    mnc = mccmnc[3:] if mccmnc and mccmnc.startswith(mcc) else imsi[3:6]

    bundle, source = find_bundle(imsi, args.bundles_dir)
    if bundle is None:
        bundle, source = discovery_bundle(mcc, mnc), "3gpp-discovery"

    msisdn = args.msisdn
    if not msisdn and own:
        msisdn = e164(own[0], mcc)
        if not msisdn:
            log(f"warning: cannot make '{own[0]}' E.164, pass --msisdn")
    if not msisdn:
        log("warning: no MSISDN; NekoIMS will register with an IMSI-based "
            "IMPU, which most operators reject")

    cfg = {"domain": bundle["domain"]}
    if msisdn:
        cfg["msisdn"] = msisdn
    cfg["impi"] = f"{imsi}@{bundle['domain']}"
    if args.pcscf:
        cfg["pcscf"] = args.pcscf
    for key in CONFIG_KEYS:
        if key in bundle and key not in cfg:
            cfg[key] = bundle[key]
    cfg["simcard_server"] = args.simcard_server
    if imei and imei.isdigit() and len(imei) == 15:
        cfg["imei"] = imei
    else:
        log(f"warning: modem IMEI '{imei}' is not 15 digits, "
            "registering without +sip.instance")

    text = json.dumps(cfg, indent=2) + "\n"
    if args.output:
        os.makedirs(os.path.dirname(os.path.abspath(args.output)),
                    exist_ok=True)
        with open(args.output, "w") as f:
            f.write(text)
        log(f"wrote {args.output}")
    else:
        sys.stdout.write(text)

    log(f"modem {modem}, carrier: {bundle.get('name', '?')} [{source}]")
    if not args.pcscf:
        log("start nekoims with -p <pcscf> (from the ePDG dialer)")
    if bundle.get("epdg"):
        log(f"ePDG dialer: epdg={bundle['epdg']} apn={bundle.get('apn', 'ims')}"
            f" mcc={mcc} mnc={mnc}")


if __name__ == "__main__":
    main()
