#!/usr/bin/env python3

# This file is entirely generated by Artificial Intelligence (AI). License may be vague.

"""
modem_usage: show or set the UE usage setting a QMI modem advertises at LTE
attach (TS 24.301 "voice domain preference and UE's usage setting").

A data-centric attach tells the network the device has no voice. With the SIM
also IMS-registered over the ePDG, that can break VoLTE (AMR) calls.

    sudo python3 tools/modem_usage.py                 # show current setting
    sudo python3 tools/modem_usage.py voice           # until modem power cycle
    sudo python3 tools/modem_usage.py data            # back to data-centric
    sudo python3 tools/modem_usage.py voice --permanent

The new setting is only sent at the next attach, so re-attach afterwards:
    sudo mmcli -m 0 --disable && sudo mmcli -m 0 --enable

Goes through qmi-proxy, so it coexists with ModemManager.
"""
import argparse
import os
import sys

import gi

gi.require_version("Qmi", "1.0")
from gi.repository import Gio, GLib, Qmi  # noqa: E402

TIMEOUT = 10


def wait(begin, finish):
    ctx = GLib.MainContext.default()
    box = {}

    def cb(_src, res, _data=None):
        try:
            box["v"] = finish(res)
        except GLib.Error as e:
            box["e"] = e

    begin(cb)
    while not box:
        ctx.iteration(True)
    if "e" in box:
        sys.exit(f"QMI error: {box['e'].message}")
    return box["v"]


def nick(enum_value) -> str:
    return enum_value.value_nick if hasattr(enum_value, "value_nick") \
        else str(enum_value)


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("usage", nargs="?", choices=["voice", "data"],
                    help="set voice-centric or data-centric (omit to show)")
    ap.add_argument("--permanent", action="store_true",
                    help="persist across modem power cycles")
    ap.add_argument("--device", default="/dev/cdc-wdm0")
    args = ap.parse_args()

    if os.geteuid() != 0:
        sys.exit("must run as root: qmi-proxy only accepts root clients")

    f = Gio.File.new_for_path(args.device)
    dev = wait(lambda cb: Qmi.Device.new(f, None, cb, None),
               Qmi.Device.new_finish)
    wait(lambda cb: dev.open(Qmi.DeviceOpenFlags.PROXY, TIMEOUT, None, cb,
                             None), dev.open_finish)
    nas = wait(lambda cb: dev.allocate_client(Qmi.Service.NAS, 0, TIMEOUT,
                                              None, cb, None),
               dev.allocate_client_finish)

    def show():
        out = wait(lambda cb: nas.get_system_selection_preference(
                       None, TIMEOUT, None, cb, None),
                   nas.get_system_selection_preference_finish)
        out.get_result()
        print(f"usage preference:        {nick(out.get_usage_preference())}")
        print(f"voice domain preference: "
              f"{nick(out.get_voice_domain_preference())}")

    try:
        if args.usage:
            inp = Qmi.MessageNasSetSystemSelectionPreferenceInput.new()
            inp.set_usage_preference(
                Qmi.NasUsagePreference.VOICE_CENTRIC if args.usage == "voice"
                else Qmi.NasUsagePreference.DATA_CENTRIC)
            inp.set_change_duration(
                Qmi.NasChangeDuration.PERMANENT if args.permanent
                else Qmi.NasChangeDuration.POWER_CYCLE)
            out = wait(lambda cb: nas.set_system_selection_preference(
                           inp, TIMEOUT, None, cb, None),
                       nas.set_system_selection_preference_finish)
            try:
                out.get_result()
            except GLib.Error as e:
                sys.exit(f"set failed: {e.message}")
            print(f"set {args.usage}-centric "
                  f"({'permanent' if args.permanent else 'until power cycle'})"
                  "; re-attach for it to take effect")
        show()
    finally:
        wait(lambda cb: dev.release_client(
                 nas, Qmi.DeviceReleaseClientFlags.RELEASE_CID, TIMEOUT, None,
                 cb, None), dev.release_client_finish)


if __name__ == "__main__":
    main()
